export const ROLE_LIMITS: Record<string, number> = {
  "President": 1,
  "Secretary": 1,
  "Treasurer": 1,
  "Chairperson": 2,
  "Vice Chairperson": 1,
  "Event Coordinator Team Lead": 1,
  "Technical Team Lead": 1,
  "Web Development Team Lead": 1,
  "Research Team Lead": 1,
  "Content Team Lead": 1,
  "Social Media Team Lead": 1,
  "Event Coordinator Team": Infinity,
  "Technical Team": Infinity,
  "Web Development Team": Infinity,
  "Research Team": Infinity,
  "Content Team": Infinity,
  "Social Media Team": Infinity,
};
